server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.163.5.178:5432/postgres
    username: jerry
    password: jerry123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.movie.movies11.models
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



